GET api.openweathermap.org/data/2.5/weather?q=london&appid=7e810f0a948a295278b64c21224ff0d2
###

GET api.openweathermap.org/data/2.5/weather?q=birmingham&appid=7e810f0a948a295278b64c21224ff0d2&units=metric